### ISSUE TITLE
update tuttleofx to 0.11.0

### ISSUE THREAD

**Issue by cbenhagen** [cbenhagen/homebrew-video#10]
let's update the forumula :)

i added
`  depends_on "cbenhagen/video/avtranscoder"`

but i get this error:
```
CMake Error at plugins/image/io/AudioVideo/avTranscoder/src/cmake_install.cmake:35 (file):
  file INSTALL cannot find
  "/tmp/tuttleofx20150428-16585-1f6pbjz/build_py2.7/plugins/image/io/AudioVideo/avTranscoder/src/libavtranscoder.a".
```

@cchampet how would i tell it to search in /usr/local/lib for it?

**Comment by cchampet** [comment]
Great move :)
Currently Tuttle has avtranscoder has a submodule with the AudioVideo plugin. So there is no dependency for the moment: the avtranscoder library is built with the AudioVideo plugin. Do you still get the error if you remove 
```
depends_on "cbenhagen/video/avtranscoder"
```
?

**Comment by cbenhagen** [comment]
Ah ok i see.

Yes i get the same error.

**Comment by cchampet** [comment]
Ok can you check PR #11 ?
Your problem is fixed with the first commit.
But now I have an issue with the last boost version versioned by homebrew (1.57):
```
/usr/local/include/boost/archive/detail/iserializer.hpp:598:13: fatal error: recursive template instantiation exceeded maximum depth of 128
```
Do you have it?

**Comment by cchampet** [comment]
Could be closed?

**Comment by cbenhagen** [comment]
sure :)
