### ISSUE TITLE
Won't install on homebrew Yosemite - could not find remote branch to clone

### ISSUE THREAD

**Issue by bengervais** [cbenhagen/homebrew-video#13]
Get this message when installing tuttleofx:

    ==> Cloning https://github.com/tuttleofx/TuttleOFX.git
    Cloning into '/Library/Caches/Homebrew/tuttleofx--git'...
    warning: Could not find remote branch release/v0.11.0 to clone.
    fatal: Remote branch release/v0.11.0 not found in upstream origin
    Error: Failed to download resource "tuttleofx"
    Failure while executing: git clone --depth 1 --branch release/v0.11.0 https://github.com/tuttleofx/TuttleOFX.git /Library/Caches/Homebrew/tuttleofx--git

**Comment by cbenhagen** [comment]
:+1: thank you for the report
