### ISSUE TITLE
tuttleofx: add clint and argcomplete

### ISSUE THREAD

**Issue by cchampet** [cbenhagen/homebrew-video#16]
Since v0.12.0, command line tools of tuttle (sam) need 2 python modules:
- clint
https://pypi.python.org/pypi/clint/
- argcomplete
https://pypi.python.org/pypi/argcomplete/0.9.0

Need to add this in the formulae (did not check):
```
depends_on "clint" => :python
depends_on "argcomplete" => :python
```

**Comment by cchampet** [comment]
And how to manage these dependencies if tuttle is installed with python3?

**Comment by cbenhagen** [comment]
what about:
```ruby
  if build.with?("python")
    depends_on "clint" => :python
    depends_on "argcomplete" => :python
  end

  if build.with?("python3")
    depends_on "clint" => :python3
    depends_on "argcomplete" => :python3
  end
```

**Comment by cchampet** [comment]
:+1:

**Comment by cbenhagen** [comment]
ok i will add this when https://github.com/tuttleofx/TuttleOFX/issues/442 is fixed

**Comment by cchampet** [comment]
We've got a compilation error on MacOS with last version:
https://github.com/tuttleofx/TuttleOFX/issues/454

Maybe because now we depend on boost-1.58 with homebrew, and something change with boost::mutex... (see Tuttle issue).
