### ISSUE TITLE
tuttleofx: make ofx plugins available by default

### ISSUE THREAD

**Issue by cbenhagen** [cbenhagen/homebrew-video#19]
@cchampet 
Should we set the default path to `/usr/local/opt/tuttleofx/OFX/`? Or just say in the 'caveats' section that the user should add this to his to his OFX_PLUGIN_PATH?

In any case i feel we should help the user to get started as easy as possible.

**Comment by cchampet** [comment]
Hello,
I agree we should give more information to the users. A good first solution is to complete 'caveats' section to give some help to the user. Something like:
```ruby
def caveats; <<-EOS.undent
    Before using TuttleOFX plugins, you need to set an environment variable to tell where are the plugins:
    export OFX_PLUGIN_PATH=/usr/local/Cellar/tuttleofx/#{version}/OFX

    For usage instructions:
        more #{opt_prefix}/USAGE.md
    EOS
```
