### ISSUE TITLE
Tuttleofx does not brew anymore

### ISSUE THREAD

**Issue by barbak** [cbenhagen/homebrew-video#21]
Hi,

Had this problem today, hope you know what is it. Seems to be a git issue.

OS X 10.9.5 (13F1134)

```bash
$ brew --version
0.9.5 (git revision 5ddb; last commit 2015-10-30)

$ brew install tuttleofx
==> Installing tuttleofx from cbenhagen/homebrew-video
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Cloning https://github.com/tuttleofx/TuttleOFX.git
Updating /Library/Caches/Homebrew/tuttleofx--git
==> Checking out tag v0.12.1
fatal: reference is not a tree: 6574e590efd2e993993cad3ddf4d7838725ca066
Unable to checkout '6574e590efd2e993993cad3ddf4d7838725ca066' in submodule path 'plugins/image/io/AudioVideo/avTranscoder'
Error: Failed to download resource "tuttleofx"
Failure while executing: git submodule -q update --init --recursive
```

Thanks for the help.
Cheers !

**Comment by fabiencastan** [comment]
Maybe you already have installed tuttle with homebrew a long time ago.
At one point, the submodule repository has changed from https://github.com/mikrosimage/avTranscoder to https://github.com/avTranscoder/avTranscoder.

And I think that git doesn't update that with the submodule update command.
So could you try `brew uninstall tuttleofx` and then `brew install tuttleofx`.

**Comment by barbak** [comment]
I started from a clean repo (```rm -rf /Library/Caches/Homebrew/```), then ```brew install tuttleofx```, evreything compile.
False alarm.
