### ISSUE TITLE
tuttleofx build error

### ISSUE THREAD

**Issue by bengervais** [cbenhagen/homebrew-video#5]
I think this is the right place to report this (please admonish accordingly if not)...

Got this error trying to install tuttleofx via homebrew on OSX 10.9.5:
`macpro:bin sandylombardi$ brew install tuttleofx
==> Installing tuttleofx from cbenhagen/homebrew-video
==> Installing tuttleofx dependency: boost
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.56.0/boo
Already downloaded: /Library/Caches/Homebrew/boost-1.56.0.tar.bz2
==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost/1.56.0 --libdir=/usr/local/C
==> ./b2 --prefix=/usr/local/Cellar/boost/1.56.0 --libdir=/usr/local/Cellar/boos
🍺  /usr/local/Cellar/boost/1.56.0: 10471 files, 438M, built in 10.1 minutes
==> Installing tuttleofx
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Cloning https://github.com/tuttleofx/TuttleOFX.git
Updating /Library/Caches/Homebrew/tuttleofx--git
==> Checking out branch develop
==> /usr/local/opt/scons/bin/scons INSTALLPATH=/private/tmp/tuttleofx-bGtxDu/ins
    target, source = self.emitter(target=tlist, source=slist, env=env)
  File "/private/tmp/tuttleofx-bGtxDu/tools/sconsProject/tools/doxygen.py", line 194:
    if not os.path.isabs(out_dir):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 61:
    return s.startswith('/')

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/cbenhagen/homebrew-video/issues
`

I'm sure this is some sort of newbie issue I'm having, but perhaps someone will pitty me and point me in the right direction...

**Comment by cbenhagen** [comment]
@bengervais does it work for you now?

**Comment by bengervais** [comment]
I'll let you know once we are back in a test environment in a couple weeks,
thanks for looking into it!

Cheers,
-ben

Ben Gervais
Production Systems Supervisor & Engineer
+1 416 951 1980 (Canada Cell)
+1 818 274 2371 (US Cell)
bengervais@gmail.com

**Comment by fabiencastan** [comment]
Could be closed?

**Comment by bengervais** [comment]
Yep, it's fixed now.  Thanks and sorry for taking so long to run it through the pipe.
